const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
; /* PartiallyEnd: #3632/scriptSetup.vue */
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("max-w-[1224px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex items-center justify-start w-[1180px] mt-[328px] mb-[100px] gap-40") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-primary text-[#333333] w-[129px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("w-[1077px] h-[4px] bg-[#DBC1AC]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("flex flex-col items-center justify-start max-w-[1224px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-medium font-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://hoste.africa/"), ...{ class: ("block mt-2 mb-2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex space-x-1 items-start") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731226/mockuuups-free-rock-iphone-15-pro-mockup_n5zgif.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731226/shortlet_admin_dashboard_wrfc5v.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731232/Shortlet_application_1_ofggno.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-medium font-secondary mb-2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://525system.com/"), ...{ class: ("block mt-2 mb-2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex space-x-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731357/mockuuups-free-rock-iphone-15-pro-mockup_hbqajf.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731357/Shortlet_application_1_wo849z.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731356/shortlet_admin_dashboard_qlgzdy.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-medium font-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://www.behance.net/gallery/189124823/United-Bank-for-Africa-Mobile-App-Redesign"), ...{ class: ("block mt-2 mb-2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex space-x-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732501/mockuuups-free-rock-iphone-15-pro-mockup_ccpsx5.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732500/shortlet_admin_dashboard_vfvask.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732501/Shortlet_application_1_vxswwg.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-medium font-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://www.behance.net/gallery/177938509/DC-FOOD-BANK-UI-Design"), ...{ class: ("block mt-2 mb2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex item-start space-x-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732574/shortlet_admin_dashboard_xzs06q.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732574/shortlet_admin_dashboard-1_aqkuyk.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732575/Shortlet_application_1_s6rztn.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-3xl font-medium font-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://www.behance.net/gallery/177594777/Everest-Crest-High-School-Site-UI-Design"), ...{ class: ("block mt-2 mb-2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex space-x-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732575/mockuuups-free-rock-iphone-15-pro-mockup_igiyl4.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737731226/shortlet_admin_dashboard_wrfc5v.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732574/shortlet_admin_dashboard-2_ekkplf.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("project-section mb-14 w-[1200px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-[32px] font-medium font-secondary") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ href: ("https://www.behance.net/gallery/177752023/WF2"), ...{ class: ("block mt-2 mb-2 text-[#333333] font-medium font-secondary text-[20px] underline") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex space-x-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732573/mockuuups-free-rock-iphone-15-pro-mockup-1_bgub6y.png"), alt: ("Traclet Project View 1"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732574/shortlet_admin_dashboard-3_zlc8ix.png"), alt: ("Traclet Project View 2"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img, __VLS_intrinsicElements.img)({ src: ("https://res.cloudinary.com/dxgoaa5mn/image/upload/v1737732575/Shortlet_application_1_-2_b4xa9r.png"), alt: ("Traclet Project View 3"), ...{ class: ("w-[400px] h-auto") }, });
    __VLS_styleScopedClasses['max-w-[1224px]'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['justify-start'];
    __VLS_styleScopedClasses['w-[1180px]'];
    __VLS_styleScopedClasses['mt-[328px]'];
    __VLS_styleScopedClasses['mb-[100px]'];
    __VLS_styleScopedClasses['gap-40'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-primary'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['w-[129px]'];
    __VLS_styleScopedClasses['w-[1077px]'];
    __VLS_styleScopedClasses['h-[4px]'];
    __VLS_styleScopedClasses['bg-[#DBC1AC]'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['justify-start'];
    __VLS_styleScopedClasses['max-w-[1224px]'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['items-start'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['item-start'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-3xl'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['project-section'];
    __VLS_styleScopedClasses['mb-14'];
    __VLS_styleScopedClasses['w-[1200px]'];
    __VLS_styleScopedClasses['text-[32px]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['block'];
    __VLS_styleScopedClasses['mt-2'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-[#333333]'];
    __VLS_styleScopedClasses['font-medium'];
    __VLS_styleScopedClasses['font-secondary'];
    __VLS_styleScopedClasses['text-[20px]'];
    __VLS_styleScopedClasses['underline'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['space-x-1'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['w-[400px]'];
    __VLS_styleScopedClasses['h-auto'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    var $el;
    return {
        attrs: {},
        slots: __VLS_slots,
        refs: $refs,
        rootEl: $el,
    };
}
;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
; /* PartiallyEnd: #4569/main.vue */
